### ISSUE TITLE
update for 4.24?

### ISSUE THREAD

**Issue by Kettenotter** [pafuhana1213/RenderWidgetToTarget#2]
Hey there,
first I want to say thank you for making this plugin available for everyone!
But sadly I can't get it working in UE4 4.24. I have only very basic knowledge of c++.

It would be amazing if you could update it to version 4.24 or help me to get it running.

compiler error: https://imgur.com/fQP2Ixy

**Comment by pafuhana1213** [comment]
Updated 4.25.4
Thanks!
